### ISSUE TITLE
Could not find template 'blank.rmd' in package 'dflow'.

### ISSUE THREAD

**Issue by rdinnager** [MilesMcBain/dflow#3]
I'm getting the following error:
```
> dflow::use_rmd("analysis.Rmd")
✔ Creating 'doc/'
Error: Could not find template 'blank.rmd' in package 'dflow'.
```

Could this be because the file is called `blank.Rmd` in the repo (e.g. capitalised)? I'm using linux so filenames are case sensitive, this would probably work in Windows though.

Thanks for the really helpful little package here by the way. I would have written this myself if you hadn't done it already (though mine would have been clunkier).  Cheers!

**Comment by MilesMcBain** [comment]
I reckon you've nailed the mistake. Thanks!

**Comment by MilesMcBain** [comment]
Pushed a commit. Let me know if issue persists. Glad you found this useful!
